name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: mozc-builder:latest
          load: true

      - name: Copy RPM package
        run: |
          id = $(docker create mozc-builder)
          docker cp $id:/home/rpm_builder/rpmbuild/RPMS ./RPMS
          docker rm $id

      - name: Upload RPM package
        uses: actions/upload-artifact@v2
        with:
          name: rpm-package
          path: ./RPMS/**/*.rpm
          if-no-files-found: error
